APP_KEY: "jpmqcnhztpnhe52"
APP_SECRET: "df4h818f7owm54l"
ACCESS_TOKEN: "dwbqoh3jhhdhoo4t"
ACCESS_TOKEN_SECRET: "bkgwtxi5u13zkd0"
USER_ID: "227455018"
DEVISE_SECRET_KEY: "4eaff45l84rnx1zyvngppj6wfm9q26jh4eaff1gqb7n8hh1gqyvngqgd5"
