#APP_KEY: "5l8fm7nu6xl48hh"
#APP_SECRET: "v8lx1zyvngqgd53"
ACCESS_TOKEN: "krn08k525k3rd15t"
ACCESS_TOKEN_SECRET: "irayaq7e8uxj21a"
USER_ID: "412282704"
DEVISE_SECRET_KEY: "4eaff45l84rnx1zyvngppj6wfm9q26jh4eaff1gqb7n8hh1gqyvngqgd5"
